# Generated by Django 3.2.6 on 2021-08-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_profile_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_order', models.DateTimeField()),
                ('time_of_delivery', models.DateTimeField()),
                ('products', models.ManyToManyField(related_name='orders', to='staff.Product')),
            ],
        ),
    ]
