# Generated by Django 3.2.6 on 2021-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210812_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_text',
            field=models.TextField(default=''),
        ),
    ]
