# Generated by Django 3.2.6 on 2021-08-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_order_bill_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custormer_phone_no',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
