# Generated by Django 3.2.6 on 2021-08-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20210812_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_of_expense', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('summary', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='custormer_phone_no',
            field=models.IntegerField(max_length=15),
        ),
    ]
