# Generated by Django 3.2.6 on 2021-08-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custormer_phone_no',
        ),
    ]
