# Generated by Django 3.2.6 on 2021-08-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_remove_order_custormer_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
