# Generated by Django 3.2.6 on 2021-08-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_order_payable_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payable_amt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
