# Generated by Django 3.2.6 on 2021-08-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='withdrawer',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
