# Generated by Django 3.2.6 on 2021-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
