# Generated by Django 3.2.6 on 2021-08-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_alter_expense_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('none', 'none'), ('biriyani', 'biriyani'), ('thali', 'thali')], default='none', max_length=25),
        ),
    ]
