# Generated by Django 4.1 on 2024-05-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('none', 'none'), ('biriyani', 'biriyani'), ('thali', 'thali'), ('chinese', 'chinese')], default='none', max_length=25),
        ),
    ]
