# Generated by Django 4.1 on 2024-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_money_online_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('none', 'none'), ('biriyani', 'biriyani'), ('thali', 'thali'), ('extra', 'extra'), ('chinese', 'chinese'), ('curry', 'curry')], default='none', max_length=25),
        ),
    ]
