# Generated by Django 4.2.13 on 2024-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_expense_is_online_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLandmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('distance', models.FloatField()),
                ('time_in_minutes', models.IntegerField()),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
