# Generated by Django 4.2.13 on 2024-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_deliverylandmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.TextField()),
                ('category', models.CharField(choices=[('none', 'none'), ('economic', 'economic'), ('delivery_rate', 'delivery_rate'), ('constant', 'constant'), ('miscellaneous', 'miscellaneous')], default='none', max_length=25)),
            ],
        ),
    ]
