# Generated by Django 4.2.13 on 2024-05-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_remove_deliverylandmark_charge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalVariables',
            new_name='GlobalVariable',
        ),
    ]
