# Generated by Django 4.2.13 on 2024-05-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_deliverylandmark_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deliverylandmark',
            name='parent',
            field=models.CharField(blank=True, default='Barasat', max_length=30),
        ),
    ]
